#
# Created by MikBac on 30.12.2024
#
services:
  postgres-db:
    container_name: postgres-db
    image: postgres:17.2
    hostname: postgres-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres1
      - POSTGRES_DB=test_db
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1g
    volumes:
      - db-test-storage:/var/lib/postgresql/data
    networks:
      - postgres-test-network

volumes:
  db-test-storage:
    name: db-test-storage
    driver: local

networks:
  postgres-test-network:
